### ISSUE TITLE
Inferno's Owner MoLuo's New liquidbounce 

### ISSUE THREAD

**Issue by KOFTWAR** [SkiderKiller/FakeBounce-Killer#13]
陌落新开了个傻逼内部
我和他闹翻了把我踹了Inferno
那个新水叫Level什么的
蒜头和他搞得
![image](https://user-images.githubusercontent.com/103908924/170451472-1cf50338-8b8f-47c6-a55f-ad72c72f22c2.png)
这B东西，你们看吧

**Comment by KOFTWAR** [comment]
成分真TM复杂

**Comment by KOFTWAR** [comment]
我有空想法子找人泄露一下

**Comment by KOFTWAR** [comment]
我们StarLight和Inferno TM现在彻底闹翻好吧

**Comment by KOFTWAR** [comment]
靠，白瞎了我转给他群主

**Comment by KOFTWAR** [comment]
就是我们StarLight的Owner之一和MoLuo玩原神急眼了，就把那个Owner踹了，然后我应那个Owner的要求把MoLuo踹了，他就把我踹出了Inferno

**Comment by KOFTWAR** [comment]
你们不会有人看不懂中文吧

**Comment by KOFTWAR** [comment]
我计划是找个他知道的Cracker拜师，他不敢不把我拉进去

**Comment by KOFTWAR** [comment]
或者找个他们内部的人

**Comment by KOFTWAR** [comment]
总之，我得到Level LB的第一时间将发送给你们

**Comment by IamAbler** [comment]
Hi,if it's not wrong,here is issue not story meeting,LOL.  
Love from Taipei

**Comment by SinoAHpx** [comment]
hilarious shit

**Comment by KOFTWAR** [comment]
![Uploading image.png…]()

**Comment by KOFTWAR** [comment]
![image](https://user-images.githubusercontent.com/103908924/170605023-44d5f16d-3aae-46a8-b293-22dba526ad78.png)

**Comment by KOFTWAR** [comment]
我大概很快就会发给你们

**Comment by K0itoyuu** [comment]
iceshadow是一个开源项目 买了只能说你被圈了

**Comment by IamAbler** [comment]
So,if you want submit a new client based on LiquidBounce,you just need to upload the jar flie instead of telling the stroy of the client.You don't seem to you can use issues correctly.  
This issue just looks like a shit.  
**_LMAO_**  
**_Love from Taipei._**

**Comment by KOFTWAR** [comment]
没事了
