### ISSUE TITLE
Found a LiquidBounce-Based Paid Client Called"Xiaoda Bounce"

### ISSUE THREAD

**Issue by liujiang71352** [SkiderKiller/FakeBounce-Killer#15]
Jar File Link:https://www.mediafire.com/file/scmgx2j85jzffa7/XiaodaBounce_New.jar/file
Chinese Link:https://wws.lanzout.com/i10Lf05k113g
Skidded From:Noteless&LiquidBounce
This client Add a built-in verification and sells to the general public without disclosing source,which is a serious violation of the original intention of the source.
(im a chinese and im using translate,if you can't understand my words,im sorry.)

**Comment by RareCO** [comment]
Thank you for helping us.
We'll handle it as soon as possible.
