### ISSUE TITLE
Is there an encryption violation for the script?

### ISSUE THREAD

**Issue by Li-Zi-stu** [SkiderKiller/FakeBounce-Killer#22]
Suppose I write a LiquidBounce script with api_version=2, can I encrypt or charge for encryption, or do I have to keep it open source?
假设我自己写了一个api_version=2的LiquidBounce脚本，我可否进行加密或者加密收费的操作，还是说我必须保持开源？

**Comment by RareCO** [comment]
Please read the GPLv3 license carefully and you'll find your answer.
We'll not handle any liquidbounce's attachments.
